project:
  type: website
  output-dir: docs
  resources:
    - images/
    - .nojekyll  # Add this line

website:
  title: "Unstandardized Accounting Terminology"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Dictionaries"
        href: 01-Dictionaries.qmd
      - text: "Textual Measures"
        href: 02-TextualMeasures.qmd
      - text: "Robustness Tests"
        href: 03-RobustnessTests.qmd
      - text: "TBD ..."
        href: 04-TBD.qmd
    right:
      - icon: github
        href: https://github.com/MatthiasUckert/UnstandardizedAccountingTerminology
        
  page-footer:
    center: "© 2025 | Supplementary materials for JAE submission"

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
    code-summary: "Show code"
    smooth-scroll: true
    link-external-newwindow: true
    grid:
      sidebar-width: 320px
    include-after-body:
      - text: |
          <script src="js/resizable-toc.js"></script>

execute:
  freeze: auto