project:
  type: website
  output-dir: docs
  resources:
    - images/
    - .nojekyll  # Add this line

website:
  title: "Unstandardized Accounting Terminology"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Terms & Concepts"
        href: 01-TermsConcepts.qmd
      - text: "Database Matching"
        href: 02-DatabaseMatching.qmd
      - text: "Name Matching Package"
        href: 03-NameMatching.qmd
    right:
      - icon: github
        href: https://github.com/MatthiasUckert/UnstandardizedAccountingTerminology
        
  page-footer:
    center: "© 2025 | Supplementary materials for JAE submission"

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
    code-summary: "Show code"
    smooth-scroll: true
    link-external-newwindow: true
    grid:
      sidebar-width: 320px

execute:
  freeze: auto